// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// vusC_full
double vusC_full(NumericVector tt1, NumericVector tt2, NumericVector tt3);
RcppExport SEXP _adjVUS_vusC_full(SEXP tt1SEXP, SEXP tt2SEXP, SEXP tt3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tt1(tt1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tt2(tt2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tt3(tt3SEXP);
    rcpp_result_gen = Rcpp::wrap(vusC_full(tt1, tt2, tt3));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adjVUS_vusC_full", (DL_FUNC) &_adjVUS_vusC_full, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_adjVUS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
