# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
vusC_full <- function(tt1, tt2, tt3) {
    .Call(`_adjVUS_vusC_full`, tt1, tt2, tt3)
}

